name: Merge Queue Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

# How will this affect the merge queue?
# Works with the only care about last queue item results setting, but a problem if that one fails
# concurrency:
#   group: merge-queue-test-${{ github.head_ref}}
#   cancel-in-progress: true

jobs:
  test-with-delay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sleep to simulate longer running test
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "This test will run for 60 seconds"
          sleep 60

      - name: Determine test outcome
        id: outcome
        run: |
          echo "that worked"

  # This job always runs last and depends on all tests
  final-check:
    name: Final verification
    needs: test-with-delay
    runs-on: ubuntu-latest
    steps:
      - name: pass_pr
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "This is a pull request"
          echo "Final check passed!"
      - name: Final check with delay
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Running final verification..."
          sleep 20
          time=$(date +%s%N | cut -b1-13)
          result=$((time % 2))
          if [ $result -eq 0 ]; then
            echo "Final check failed!"
            exit 1
          else
            echo "Final check passed!"
          fi
